LPAR activate C sample
IBM/zOS-BCPii pull request #3
Opened 2021-04-08 12:51 UTC by gorelikg

2021-04-09 16:48 UTC, blairwyman commented on Example-LPARActivate-C/cpp/hwirstc1.cpp
> +void printConstTextStr(int len, const char *text, char *description)
Calls to this function could be safely replaced with `printf("* >%s: %.*s", description, len, text);`

2021-04-15 11:57 UTC, bnoordyke commented on Example-LPARActivate-C/cpp/hwirstc1.cpp
> +*    MODULE NAME= HWIRTC1                                             *
The Module Name needs an 'S' in it.

2021-04-15 12:17 UTC, bnoordyke requested changes
Update the Module Name in the prologue in hwirstc1.cpp.

2021-04-15 14:28 UTC, merged

2021-04-15 14:45 UTC, bnoordyke reviewed
Looks good to me.